apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-nexus.fullname" . }}
  labels:
    {{- include "ai-nexus.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.monitoring.enabled }}
  - port: {{ .Values.monitoring.prometheus.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  {{- if .Values.distributed.enabled }}
  - port: {{ .Values.distributed.masterPort }}
    targetPort: dist-master
    protocol: TCP
    name: dist-master
  {{- end }}
  selector:
    {{- include "ai-nexus.selectorLabels" . | nindent 4 }}
